---

### Install Prerequisite packages

- name: Add PHP repo
  apt_repository: repo='ppa:ondrej/php5-oldstable' state=present
  notify: update apt-cache

- name: Install PHP packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - php5-fpm
    - php5-mcrypt
    - php5-cli
    - php5-sqlite
    - php5-curl

