---

- include: rhel.yml
  when: ansible_os_family in [ 'CentOS', 'RedHat' ]

- name: Install Nginx.conf
  sudo: yes
  template: src='nginx.conf.j2' dest='/etc/nginx/conf.d/tanks.conf'
  notify:
    - restart nginx


#- name: Configure Cronjob
#  cron: name="Run Tanks Round" minute="*" user="{{ user }}" job="cd {{ tanks.path }}; ./run-tanks tanks/*" cron_file=tanks
